server:
  servlet:
    context-path: /uaa
  port: 5000

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/social_diagnostic?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  jwt:
    key: jh2GnQGWZ3tuEcSD

auth:
  properties:
    web-portal: gCxq2eTz
    mobile-app: udUA43Y9
    social-diagnostica-service: wV6wC8s6