spring:
  application:
    name: gateway

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /uaa/**
      serviceId: auth-service

    social-diagnostica-api:
      path: /soicialDiagnostica/**
      serviceId: social-diagnostica-api

server:
  port: 4000